org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14
fabric_version=0.92.6+1.20.1

mod_version=1.0.0
maven_group=dev.kkayam
archives_base_name=infinite-stack-in-storage

# Modrinth project id or slug (set after creating the project on modrinth.com)
modrinth_project_id=infinite-stack-in-storage
